
module.exports = {
  name: "sövçok",
  description: "yardım",
  execute(client, message, args) {
    message.channel.send(`ananın amına teletabinin antenlerini sokar göbeğindeki televizyondan ulusal porno yayını yaparımananı özgürlük heykelinin yanmayan meşalesinde siker şehri duman ederimhollywood bulvarında donla gezen ananın amına topuklu ayakkabı sokayımananı ikiz kulelerinin yedinci katına cıkartır amına uçakla girerim..ananın o dazlak kafasına teflon tavayla vurur sersemletir sikerim.ananın buruşmuş amına tefal ütü basar dümdüz ederim.ananın amına windows 7 kurar mavi ekran hatası verinceye kadar sikerim.ananın amına telefon kablosu sokar paralel hattan bacını skermgardolapta tangasını arayan ananın kafasını dolap kapagına sıkıştırır müjde ar gibi sikerimdağdan inmediği icin yüzme bilmeyen ananı büyük pasificte 1 ton boşalan beyaz balinalarla beraber-- siker olimpiyat yüzme şampiyonasında altın madalya kazandırırımkırmızı eşarp giyip ormanda kırmızı başlıklı kız gibi takılan anana kurt gibi yaklaşır amını param parça ederimmmpikachuuuuuuuuu diye camdan atlayan sipastik ananın amına poke topu fırlatırımananı balbasaurun sarmaşık kırbacıyla dolar pikacuyla kanka olur veririm elektriğiedisonla kanka olur ananı fakir mahallenizde yanmayan sokak direğine bağlar sike sike trafoyu patlatırımhani benim gençliğim nerde diyen orospu cocugu seni.`)
    message.channel.send(`tavşan kostümü giyip fotograf cektirince kendini playboy dergisinde kapak sanan ananın amına evdeki elektrik süpürgesini sokarımananla karşılıklı salsa yaparken piste takla atarak giren orospu cocugu kardeşini götünden sikerim..ananla karşılıklı sikişirken ay çekirdeği cıtlatırım kabuklarını babanın suratına fırlatırımevde göbeğini yere deydirerek sınav cekince kendini atletik sanan abini götünden sikeyim...saclarını arkaya tarayınca kendini tarık akan sanan babanıda götünden sikeyim...tokyo drifti izleyip köyde traktörle drift yapmaya calısan abinin götüne kamyonla gireyim..kilotlu corapla denize giren kız kardeşinin kafasını suya sokup bogulana kadar sikeyim..ananı çeeeeeeeeeeeeeeee ..googleye türbanlı karı sikişleri yazan dedeni götünden sikeyim.camiden tabut calıp dedesine tabut satan ananı tabutun icinde siker öldürürüm...ananın amına kolumu sokar kücük kardeşlerini cıkartırımananı neil amstrongla beraber aya cıkartıp siker hardcore movie alırım altın portakal film festivalinde aldıgım ödülü ananın amına sokarımananın amına harry poterin assasını sokar kücük kücük büyücüler cıkartırım`)
     message.channel.send(`ananın amına pandora kutusu sokar icinden tavşan cıkartırımananın amına duracel pill atar 10 kata kadar daha güçlü sikerim.ananı national geographic belgeselinde sikerim insanlar arslan ciftlesmesi görür..ananın amına 5+1 hoparlör sokar kolonları titretirimananı hollandadaki altın portakal film festivaline götürür amına portakal ağacını sokarımanana gerilla kostümü giydirir şanlı türk ordusunun icine atıp harmandalı oynattıktan sonra amına c4 yerlestirip havaya ucururumananı ramsstein konserinde pistte sikerim du hast şarkısını tersten okuttururumbabanın o kokmuş corabını ananın amına sokarımananı galatasaray fenerbahçe derbisinde kale yapar musa sow gibi hatrick yaparımkaradenizin cılgın dalgalarında sörf yapmaya calısırqene diye fotograf cektiren bacının amına sörf tahtasını sokarımananın amına nokia 3310 sokar polifonik müzik eşliğinde sikerim.ananı klavyemin üstünde sikerken paintte yarak resmi cizip kız kardeşine gönderirim.`)
    message.channel.send(`ananı jerry kılıgına sokar tom gibi kovalarım elbet bir köşede yakalar sikerim.hain antuan diye haykıran kız kardeşini atımın üstünde yan giderken siker öldürürüm.ananı afrikada am kıtlığı yaşayan 3 bacaklı familyasının arasına atar paramparça olana kadar sikerim.ananı bruce lee gibi havada 30 parande atarak sikerimananı barnebau stadınnın orta sahasında sikerim 70 milyon ispanyol ollaaaaa diye bagırır ..ananla karşılıklı okey oynuyum okeyi ananın kafasına vurayım beyin trawmesi gecirriken sikerimananın amına polis jobu sokar ay memur bey lütfen yavaş olun diye çığlık attırırımananı hamit gibi 365 gün siker geriye kalan 6 saatte direğe vururumananı ağrı dağının eteğinde sikerim ibrahim tatlıses halay çekerananın amına kemençe sokar üzerinde horon teperimalt alta ben orospu cocuguyum yazınca kendini akrostiş şiir yazdım sanan orospu cocuguananla yamyam ayininde karşılıklı barış çubuğu içer totem heykelinin tepesine oturttururuminşaat direğinde striptiz yapmaya calısırken bacagını kıran ananın kafasına kiremit atar bayıltıp sikerim`)
  }};